---
collections:
  - name: ansible.posix
    version: 1.4.0

  - name: community.docker
    version: 2.7.0

  - name: community.general
    version: 5.3.0

  - name: devsec.hardening
    version: 7.14.3

  - name: community.crypto
    version: 2.4.0
