---
collections:
  - name: ansible.posix
    version: 1.4.0

  - name: community.docker
    version: 2.7.0

  - name: community.general
    version: 5.1.1

  - name: devsec.hardening
    version: 7.15.0

  - name: community.crypto
    version: 2.4.0
