---
exclude: |
  (?x)^(
      inventory.yml|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-symlinks
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible/ansible-lint
    rev: v6.3.0
    hooks:
      - id: ansible-lint

  - repo: https://github.com/rwxd/pre-commit-hooks
    rev: v1.2.1
    hooks:
      - id: terraform-fmt
