---
- name: unattended-upgrades
  src: https://github.com/jnv/ansible-role-unattended-upgrades.git
  scm: git
  version: v1.12.2

- name: geerlingguy.docker
  src: https://github.com/geerlingguy/ansible-role-docker.git
  scm: git
  version: 4.2.4

- name: geerlingguy.pip
  src: https://github.com/geerlingguy/ansible-role-pip.git
  scm: git
  version: 2.1.0

- name: ansible-role-k3s
  src: https://github.com/PyratLabs/ansible-role-k3s.git
  scm: git
  version: v3.2.0

- name: ansible-disk
  src: https://github.com/AerisCloud/ansible-disk.git
  scm: git
  version: v.2.6.3
