---
- name: Check repopass defined
  ansible.builtin.assert:
    that: borgbackup_repopass is defined

- name: Install borg
  ansible.builtin.package:
    name: borg
    state: present
  become: true
  when: ansible_distribution in ["Archlinux"]

- name: Install borgbackup
  ansible.builtin.package:
    name: borgbackup
    state: present
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Create borgbackup key directory
  ansible.builtin.file:
    path: "{{ borgbackup_key_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Check if config exists
  ansible.builtin.stat:
    path: "{{ borgbackup_hetzner_config }}"
  register: config_file_result

- name: borg - create log dir
  ansible.builtin.file:
    path: "{{ borgbackup_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0600
