---
- name: Create cloudflare_exporter directory
  ansible.builtin.file:
    path: "{{ cloudflare_exporter_container_dir }}"
    owner: "{{ cloudflare_exporter_container_user_id }}"
    group: "{{ cloudflare_exporter_container_group_id }}"
    mode: 0740
    state: directory
  become: true

- name: Create container networks
  docker_network:
    name: "{{ item.name }}"
    state: present
  become: true
  with_items: "{{ cloudflare_exporter_container_networks + cloudflare_exporter_container_networks_custom  }}"

- name: Make sure the cloudflare_exporter container is created and running
  docker_container:
    name: "{{ cloudflare_exporter_container_name }}"
    image: "{{ cloudflare_exporter_container_image }}"
    pull: true
    state: "{{ cloudflare_exporter_container_state }}"
    env: "{{ cloudflare_exporter_container_env | combine(cloudflare_exporter_container_env_custom) }}"
    ports: "{{ cloudflare_exporter_container_ports }}"
    volumes: []
    networks: "{{ cloudflare_exporter_container_networks + cloudflare_exporter_container_networks_custom  }}"
    restart_policy: "{{ cloudflare_exporter_container_restart_policy }}"
    labels: "{{ cloudflare_exporter_container_labels | combine(cloudflare_exporter_container_labels_custom) }}"
    command: "{{ cloudflare_exporter_container_commands + cloudflare_exporter_container_commands_custom }}"
    log_driver: json-file
    log_opt:
      max-size: 10m
  become: true
