---
- name: Disable Password Authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    backup: true
  notify: restart sshd
  become: true

- name: Disable Root Login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    backup: true
  notify: restart sshd
  become: true

- name: Change Max Authentication Tries -> 10
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^MaxAuthTries"
    line: "MaxAuthTries 10"
    state: present
    backup: true
  notify: restart sshd
  become: true

- name: Change PubkeyAuthentication -> true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present
    backup: true
  notify: restart sshd
  become: true

- name: Change AuthenticationMethods -> publickey
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AuthenticationMethods"
    line: "AuthenticationMethods publickey"
    state: present
    backup: true
  notify: restart sshd
  become: true

- name: Denying user pi and ubuntu
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^DenyUsers"
    line: "DenyUsers pi, ubuntu"
    state: present
    backup: true
  become: true
