---
- name: Create speedtest_exporter directory
  ansible.builtin.file:
    path: "{{ speedtest_exporter_container_dir }}"
    owner: "{{ speedtest_exporter_container_user_id }}"
    group: "{{ speedtest_exporter_container_group_id }}"
    mode: 0740
    state: directory
  become: true

- name: Create container networks
  docker_network:
    name: "{{ item.name }}"
    state: present
  become: true
  with_items: "{{ speedtest_exporter_container_networks + speedtest_exporter_container_networks_custom  }}"

- name: Make sure the speedtest_exporter container is created and running
  docker_container:
    name: "{{ speedtest_exporter_container_name }}"
    image: "{{ speedtest_exporter_container_image }}"
    pull: true
    state: "{{ speedtest_exporter_container_state }}"
    env: "{{ speedtest_exporter_container_env | combine(speedtest_exporter_container_env_custom) }}"
    ports: "{{ speedtest_exporter_container_ports }}"
    volumes: []
    networks: "{{ speedtest_exporter_container_networks + speedtest_exporter_container_networks_custom  }}"
    restart_policy: "{{ speedtest_exporter_container_restart_policy }}"
    labels: "{{ speedtest_exporter_container_labels | combine(speedtest_exporter_container_labels_custom) }}"
    command: "{{ speedtest_exporter_container_commands + speedtest_exporter_container_commands_custom }}"
    log_driver: json-file
    log_opt:
      max-size: 10m
  become: true
