---
borgbackup_hetzner_server_id: 21923912
borgbackup_hetzner_storagebox_id: changeme
borgbackup_hetzner_storagebox_port: 23

borgbackup_hetzner_storagebox_main_user: ""
borgbackup_hetzner_storagebox_main_storagebox: "{{ borgbackup_hetzner_storagebox_main_user }}.your-storagebox.de"
borgbackup_hetzner_storagebox_main_dir: backup

borgbackup_hetzner_robot_webservice_user: changeme
borgbackup_hetzner_robot_webservice_pass: changeme

borgbackup_hetzner_storagebox_domain: "your-backup.de"

borgbackup_hetzner_storagebox_main_ssh_key: /root/.ssh/id_rsa
