---
cloudflare_ddns_container_name: "cloudflare-ddns"
cloudflare_ddns_container_image: "oznu/cloudflare-ddns:latest"
cloudflare_ddns_container_user_id: 1000
cloudflare_ddns_container_group_id: 1000
cloudflare_ddns_container_user: cloudflare_ddns
cloudflare_ddns_container_api_token: ""
cloudflare_ddns_container_zone: ""
cloudflare_ddns_container_subdomain: "ddns"
cloudflare_ddns_container_proxied: "false"
cloudflare_ddns_container_env_v4:
  "PUID": "{{ cloudflare_ddns_container_user_id | quote }}"
  "PGID": "{{ cloudflare_ddns_container_group_id | quote }}"
  "TZ": "{{ cloudflare_ddns_container_timezone | default('Europe/Berlin') | quote }}"
  "API_KEY": "{{ cloudflare_ddns_container_api_token | quote }}"
  "ZONE": "{{ cloudflare_ddns_container_zone | quote }}"
  "SUBDOMAIN": "{{ cloudflare_ddns_container_subdomain | quote }}"
  "PROXIED": "{{ cloudflare_ddns_container_proxied | string | lower | quote }}"
  "RRTYPE": "{{ 'A' | quote }}"
cloudflare_ddns_container_env_v6:
  "PUID": "{{ cloudflare_ddns_container_user_id | quote }}"
  "PGID": "{{ cloudflare_ddns_container_group_id | quote }}"
  "TZ": "{{ cloudflare_ddns_container_timezone | default('Europe/Berlin') | quote }}"
  "API_KEY": "{{ cloudflare_ddns_container_api_token | quote }}"
  "ZONE": "{{ cloudflare_ddns_container_zone | quote }}"
  "SUBDOMAIN": "{{ cloudflare_ddns_container_subdomain | quote }}"
  "PROXIED": "{{ cloudflare_ddns_container_proxied | string | lower | quote }}"
  "RRTYPE": "{{ 'AAAA' | quote }}"
cloudflare_ddns_container_state: "started"
cloudflare_ddns_container_restart_policy: "unless-stopped"
cloudflare_ddns_container_ipv4_record: true
cloudflare_ddns_container_ipv6_record: false
