---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true
  notify: Reboot

- name: Check for cloud dir
  ansible.builtin.stat:
    path: "/etc/cloud"
  register: cloud_dir
  become: true

- name: Disable cloud config
  ansible.builtin.file:
    path: "/etc/cloud/cloud-init.disabled"
    state: touch
    owner: root
    group: root
    mode: 0644
    modification_time: preserve
    access_time: preserve
  become: true
  when: >
    ansible_distribution in ["Ubuntu"]
    and cloud_dir.stat.exists

- name: Install some troubleshooting tools
  ansible.builtin.package:
    name:
      - iotop
    state: present
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
