---
- name: Configure wallabag
  hosts: all
  debugger: on_failed
  gather_facts: false
  tasks:
    - name: Include docker-wallabag role
      ansible.builtin.include_role:
        name: docker-wallabag
        apply:
          tags: wallabag
      when: wallabag_container is defined and wallabag_container
      tags: wallabag

    - name: Copy postgresql backup script
      ansible.builtin.copy:
        src: ../scripts/docker-postgres-backup
        dest: /usr/local/bin/docker-postgres-backup
        mode: 0700
        owner: root
        group: root
      become: true
      when: wallabag_container is defined and wallabag_container
      tags: wallabag
