---
- name: Configure infrastructure
  hosts: all
  become: true
  tasks:
    - name: Configure unattended-upgrades
      include_role:
        name: unattended-upgrades
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Update system
      include_role:
        name: update

    - name: Configure Borgbackup
      include_role:
        name: borgbackup_hetzner
      when: borgbackup_enabled
